require_relative "tile/base_test"
require_relative "tile/rally_point_test"
require_relative "tile/meadow_test"
require_relative "tile/mountain_test"
require_relative "tile/forest_test"
require_relative "tile/sea_test"
require_relative "towers/arrow_tower_test"
